Agregas mas pruebas a la unidad GetClientAsync_ExistingClient_ReturnClient
msmdotnet/IDPLibrary pull request #7
Opened 2023-06-08 10:48 UTC by drualcman

Solo para que se puedan hacer algunas pruebas mas

2023-06-08 11:05 UTC, drualcman commented
Cuando implemente el GetClientAsync me lo ha mantenido en el mismo pull request. Pero bueno. Aqui ya esta todo. En local me pasaba las pruebas, incluidas las nuevas que puse cuando hablamamos ayer por la tarde (hoy por la mañana para mi) de comprobar que no vengan nullos o espacios en blanco en el ClientId y/o RedirectUri.

2023-06-08 19:42 UTC, msmdotnet requested changes

2023-06-08 19:42 UTC, msmdotnet commented on src/IDPLibrary/IDPLibrary.Clients/Specifications/ClientSpecification.cs
> +internal class ClientSpecification
¿Quién consume a esta clase?

2023-06-08 19:42 UTC, msmdotnet commented on src/IDPLibrary/IDPLibrary.Clients/ClientProvider.cs
> +internal class ClientProvider : IClientProvider
¿Esta clase está repetida?

2023-06-08 21:24 UTC, drualcman commented on src/IDPLibrary/IDPLibrary.Clients/Specifications/ClientSpecification.cs
> +internal class ClientSpecification
Se me olvido eliminar el proyecto viejo.

2023-06-08 21:25 UTC, drualcman commented on src/IDPLibrary/IDPLibrary.Clients/ClientProvider.cs
> +internal class ClientProvider : IClientProvider
Igual todo esto es el proyecto viejo que se me olvido eliminar. Ya lo quite he hice pull

2023-06-09 04:16 UTC, msmdotnet approved these changes

2023-06-09 04:18 UTC, merged